### ISSUE TITLE
How good are WCS?

### ISSUE THREAD

**Issue by bodewits** [mkelley/41P-LCO#1]
DB compared WCS with DSS : good.
How good is Horizons + pointing? Scatter in position?

**Comment by mkelley** [comment]
I'm finding offsets from PS1 catalog of <1" RMS.  Great agreement!

**Comment by bodewits** [comment]
I had indeed blinked several frames and found good agreement. Surprised 
that JY said it wasnt so good for CSS, but things may improve now he has 
the E91 rather than E90 data.
