### ISSUE TITLE
Calibrate image with PanSTARRS

### ISSUE THREAD

**Issue by mkelley** [mkelley/41P-LCO#10]
Compare image photometry to PS1 catalog and determine magnitude zeropoint.

**Comment by mkelley** [comment]
Draft calibration table attached.
[calibrate.txt](https://github.com/mkelley/41P-LCO/files/886303/calibrate.txt)

**Comment by mkelley** [comment]
Please review.  Airmass might be an important column to add.

**Comment by bodewits** [comment]
What are scmean(dm), scmedian(dm), scstdev(dm)? Panstarrs values? Second, add seeing from average FWHM (given by SEP for each source)

**Comment by mkelley** [comment]
"sc" = sigma clipped.  I'll add that to the comments.

FWHM: got it.

**Comment by bodewits** [comment]
so one line for every object in the frame?

**Comment by mkelley** [comment]
These are averages for all objects matched to PS1.

**Comment by bodewits** [comment]
excellent. Binning. You already have STDEV which will feed into the error analysis.

**Comment by bodewits** [comment]
mean background, is also an output from SEP

**Comment by mkelley** [comment]
Binning?

**Comment by bodewits** [comment]
binning is standard 1x1 but there have been images in 2x2

**Comment by mkelley** [comment]
This doesn't affect calibration, but I will add it to the observing log ( #6 ).
