### ISSUE TITLE
Verify e91 table reliability

### ISSUE THREAD

**Issue by bodewits** [mkelley/41P-LCO#3]

**Comment by mkelley** [comment]
looking at the calibrated table containing RA and DEC and magnitude for all sources, look for the magnitude of the target based on inputs of astrometry, plotting the magnitude vs time such that we see whether it fluctuates or it presents a trend

**Comment by mkelley** [comment]
Draft geometry table attached.
[geometry.txt](https://github.com/mkelley/41P-LCO/files/883893/geometry.txt)

**Comment by mkelley** [comment]
I'm closing this issue because it is too open ended.  If needed, open new issues with more specific tasks.  Thanks!
