### ISSUE TITLE
Plot rh = r - 5*log10 (Delta) to take out geometry 

### ISSUE THREAD

**Issue by bodewits** [mkelley/41P-LCO#32]

**Comment by mkelley** [comment]
We are presently plotting with fixed-angular size apertures, so I've implemented the correction as 2.5 * log10(Delta):
![rp-vs-rh](https://cloud.githubusercontent.com/assets/1138643/25304887/6302804e-273e-11e7-90e4-6ea5090840d3.png)

**Comment by mkelley** [comment]
Done: PR #36
