### ISSUE TITLE
Observing log wish list?

### ISSUE THREAD

**Issue by mkelley** [mkelley/41P-LCO#6]
What is needed in the observing log?  I currently have frame name, date & time (UTC), exposure time, and filter.

**Comment by mkelley** [comment]
Time is mid-point of the exposure.

**Comment by bodewits** [comment]
rh, D? or do we do that in the 'report table'?

**Comment by mkelley** [comment]
I can add them if they are useful there.  They will for sure be in the comet data table.

**Comment by mkelley** [comment]
+Airmass

**Comment by mkelley** [comment]
Draft observing log attached.  All geometry info is saved to a separate table (See Issue #3 )
[observing-log.txt](https://github.com/mkelley/41P-LCO/files/883898/observing-log.txt)
